[features]
seeds = false
skip-lint = false

[programs.localnet]
idl_protocol = "BSn7neicVV2kEzgaZmd6tZEBm4tdgzBRyELov65Lq7dt"
idl_stableswap = "EFsgmpbKifyA75ZY5NPHQxrtuAHHB6sYnoGkLi6xoTte"

[programs.devnet]
idl_protocol = "BSn7neicVV2kEzgaZmd6tZEBm4tdgzBRyELov65Lq7dt"
idl_stableswap = "EFsgmpbKifyA75ZY5NPHQxrtuAHHB6sYnoGkLi6xoTte"

[programs.mainnet]
idl_protocol = "BSn7neicVV2kEzgaZmd6tZEBm4tdgzBRyELov65Lq7dt"
idl_stableswap = "EFsgmpbKifyA75ZY5NPHQxrtuAHHB6sYnoGkLi6xoTte"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
